project_id = "mawada-project"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.invitation-admin]
verify_jwt = true

[functions.invitation-public]
verify_jwt = false
